travis:
  secure:
    BINSTAR_TOKEN: ZwdQjvO1Z0l3CBqH4aVAsX2L5IkLGNFnUYvjmNeuDwsEW7W+nRm/+olTqCsavefBQnbhiMpSWKNfwsL04Hz7rN5jPK052+JbNFEF5tcPqdeiJvKTaeMSq6gvhoDIuAPrkLvCbUHqaEiMcYLlpJrzBROeDW3FhxqTcGvqdnqNHs/mtniyS+BaceHD4qFCDpt0TKmBsgWHE+fkg6tq2qldwBlG2YdGBPmw+T0f16op9NpixF1RSExnY6HkT/SiAzCQWya6JYLOzNd1dLN808pFyMkQkJIyfFEgRl8atrWr1wdDbisgkJWyHEQ+KGHGpVWNNkQPaFe4zNWArpsmzWw3MOKxp4DsRhqpaSLqViaehRSKMBwLA2Aq0gpMiZuhkwfcFFX/eEH0LHiGwoPVK9V9XFXcvLKNBHSwz2CzcamfYYDzKuYtjPZuFA/ehP4LbnUyqkrymB4SlswyjeldS2EkIucZSLbC0CGWE8F+h8JsoSD6TUuwt9hVWmlfh8P22hKqLQkDifsyJiDyRSecPog7O/wdvchUYMVyQpwI6x9W4639+Ehu/hVBf9cW2fmytpzoAxNYmlPNJwslH5E7OMos3MpueJp3qGWYdu//HDisQ0Ad9MAxEgve7Y4hZb13p2aU0BSPM4NY7hVAKdldo+2kT56Ut2oqwa0xcQL+01vmUX4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
